//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Api.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu phù hợp !.
        /// </summary>
        public static string Error_Msg_NoContent {
            get {
                return ResourceManager.GetString("Error_Msg_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ CSKH !.
        /// </summary>
        public static string Exception_Msg_Common {
            get {
                return ResourceManager.GetString("Exception_Msg_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến máy chủ dữ liệu, vui lòng liên hệ CSKH !.
        /// </summary>
        public static string Exception_Msg_DBConnection {
            get {
                return ResourceManager.GetString("Exception_Msg_DBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một trong các trường bị trùng. Vui lòng kiểm tra lại !.
        /// </summary>
        public static string Exception_Msg_DuplicateField {
            get {
                return ResourceManager.GetString("Exception_Msg_DuplicateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bị bỏ trống !.
        /// </summary>
        public static string Exception_Msg_EmptyField {
            get {
                return ResourceManager.GetString("Exception_Msg_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trên server dữ liệu , vui lòng liên hệ CSKH !.
        /// </summary>
        public static string Exception_Msg_InvalidDBData {
            get {
                return ResourceManager.GetString("Exception_Msg_InvalidDBData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ, vui lòng kiểm tra lại hoặc liên hệ CSKH !.
        /// </summary>
        public static string Exception_Msg_InvalidInputData {
            get {
                return ResourceManager.GetString("Exception_Msg_InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception_Msg_InvalidParameter.
        /// </summary>
        public static string Exception_Msg_InvalidParameter {
            get {
                return ResourceManager.GetString("Exception_Msg_InvalidParameter", resourceCulture);
            }
        }
    }
}
